from __future__ import annotations

from typing import Any, Iterable


def _normalize_boards(values: Iterable[str]) -> list[str]:
    ordered: list[str] = []
    for value in values:
        cleaned = str(value or "").strip().lower()
        if cleaned and cleaned not in ordered:
            ordered.append(cleaned)
    return ordered


BOOTSTRAP_PORTAL_BOARDS: dict[str, list[str]] = {
    "greenhouse": _normalize_boards(
        [
            "affirm",
            "airbyte",
            "asana",
            "benchling",
            "brex",
            "clickhouse",
            "cloudflare",
            "coinbase",
            "coursera",
            "datadog",
            "discord",
            "doordash",
            "dropbox",
            "figma",
            "flexport",
            "gusto",
            "hashicorp",
            "instacart",
            "mongodb",
            "netlify",
            "notion",
            "plaid",
            "ramp",
            "reddit",
            "replit",
            "rippling",
            "robinhood",
            "scaleai",
            "segment",
            "sentry",
            "snowflake",
            "sourcegraph",
            "spotify",
            "stripe",
            "turo",
            "twilio",
            "vercel",
            "webflow",
            "zapier",
            "lyft",
            "twitch",
            "pinterest",
            "squarespace",
            "hubspot",
            "elastic",
            "okta",
            "pagerduty",
            "toast",
            "duolingo",
            "unity",
            "roku",
            "palantir",
            "docusign",
            "qualtrics",
            "zscaler",
            "crowdstrike",
            "gitlab",
            "confluent",
            "dbt-labs",
            "fivetran",
            "sumo-logic",
            "new-relic",
            "splunk",
            "dynatrace",
            "harness",
            "launchdarkly",
            "circleci",
            "sonarqube",
            "miro",
            "canva",
            "airtable",
            "coda",
            "loom",
            "marqeta",
            "chime",
            "currentmobile",
            "dave",
            "greenlight",
            "varo",
            "upgrade",
            "parafin",
            "mercury",
            "melio",
            "payoneer",
            "remitly",
            "wise",
            "checkout",
            "nuvei",
            "tabapay",
            "alloy",
            "sardine",
            "lithic",
            "moov",
            "column",
            "treasuryprime",
            "unit",
            "synctera",
            "bond",
            "galileofinancial",
            "moderntreasury",
            "increase",
            "stax",
            "finix",
            "justworks",
            "deel",
            "oysterhr",
            "remote",
            "papaya-global",
            "letsdeel",
            "velocityglobal",
            "tempus",
            "flatiron",
            "veracyte",
            "guardanthealth",
            "grail",
            "adaptivebiotech",
            "recursionpharma",
            "insitro",
            "color",
            "devoted",
            "cityblock",
            "omadahealth",
            "osfdigitalhealth",
            "noom",
            "ro",
            "hims",
            "cerebral",
            "springhealth",
            "headway",
            "alma",
            "talkiatry",
            "lyrahealth",
            "modernhealth",
            "ginger",
            "virta",
            "livongo",
            "teladoc",
            "aledade",
            "cityblockhealth",
            "shopify",
            "etsy",
            "poshmark",
            "mercari",
            "offerup",
            "depop",
            "faire",
            "whatnot",
            "goat",
            "stockx",
            "grailed",
            "threadup",
            "fanatics",
            "chewy",
            "wayfair",
            "wish",
            "zulily",
            "servicenow",
            "workday",
            "veeva",
            "procore",
            "braze",
            "iterable",
            "klaviyo",
            "attentive",
            "postscript",
            "sendbird",
            "twilio-segment",
            "contentful",
            "sanity",
            "prismic",
            "storyblok",
            "algolia",
            "typesense",
            "meilisearch",
            "auth0",
            "descope",
            "stytch",
            "clerk",
            "temporal",
            "prefect",
            "dagster",
            "snyk",
            "lacework",
            "wiz",
            "orca-security",
            "bridgecrew",
            "vanta",
            "drata",
            "secureframe",
            "tugboat-logic",
            "openai",
            "anthropic",
            "huggingface",
            "cohere",
            "mistral",
            "databricks",
            "anyscale",
            "modal",
            "replicate",
            "together",
            "pinecone",
            "weaviate",
            "qdrant",
            "chroma",
            "langchain",
            "llamaindex",
            "weights-and-biases",
            "neptune",
            "labelbox",
            "scale",
            "surge-ai",
            "snorkel",
            "jasper",
            "copy-ai",
            "writer",
            "grammarly",
            "midjourney",
            "runway",
            "stability",
            "descript",
            "deepgram",
            "assemblyai",
            "rev",
            "speechmatics",
            "shield-ai",
            "anduril",
            "skydio",
            "joby",
            "archer",
            "github",
            "atlassian",
            "jetbrains",
            "postman",
            "insomnia",
            "render",
            "railway",
            "fly",
            "supabase",
            "neon",
            "planetscale",
            "cockroach-labs",
            "timescale",
            "crunchy-data",
            "grafana-labs",
            "chronosphere",
            "lightstep",
            "tailscale",
            "ngrok",
            "fastly",
            "akamai",
            "pulumi",
            "env0",
            "spacelift",
            "terraform",
            "retool",
            "appsmith",
            "tooljet",
            "budibase",
            "linear",
            "shortcut",
            "height",
            "plane",
            "sentinelone",
            "paloaltonetworks",
            "fortinet",
            "checkpoint",
            "tenable",
            "rapid7",
            "qualys",
            "bugcrowd",
            "hackerone",
            "1password",
            "bitwarden",
            "dashlane",
            "keeper",
            "abnormalsecurity",
            "material-security",
            "tessian",
            "looker",
            "mode",
            "hex",
            "count",
            "lightdash",
            "stitch",
            "hevo",
            "census",
            "hightouch",
            "rudderstack",
            "amplitude",
            "mixpanel",
            "heap",
            "fullstory",
            "logrocket",
            "snowplow",
            "matomo",
            "posthog",
            "docker",
            "rancher",
            "portainer",
            "coreweave",
            "lambda",
            "paperspace",
            "vast-ai",
            "materialize",
            "rockset",
            "starrocks",
            "chegg",
            "udemy",
            "skillshare",
            "masterclass",
            "khan-academy",
            "quizlet",
            "brainly",
            "instructure",
            "blackboard",
            "d2l",
            "anthology",
            "handshake",
            "ripplematch",
            "joinhandshake",
            "zillow",
            "redfin",
            "opendoor",
            "offerpad",
            "compass",
            "divvy",
            "bungalow",
            "latch",
            "smartrent",
            "project44",
            "fourkites",
            "samsara",
            "motive",
            "keeptruckin",
            "convoy",
            "uber-freight",
            "lalamove",
            "bringg",
            "onfleet",
            "routific",
            "riotgames",
            "epicgames",
            "valve",
            "bungie",
            "nianticlabs",
            "supercell",
            "scopely",
            "zynga",
            "roblox",
            "netflix",
            "hulu",
            "paramountplus",
            "peacock",
            "nytimes",
            "washingtonpost",
            "vox-media",
            "buzzfeed",
            "substack",
            "medium",
            "ghost",
            "capitalone",
            "jpmorgan",
            "goldmansachs",
            "morganstanley",
            "citadel",
            "twosigma",
            "janestreet",
            "deshaw",
            "bloomberg",
            "optiver",
            "imc",
            "hrt",
            "virtu",
            "jumptrading",
            "drw",
            "meta",
            "google",
            "amazon",
            "apple",
            "microsoft",
        ]
    ),
    # Lever seeds are kept minimal — only boards verified active as of April 2026.
    # Many companies (airtable, benchling, brex, gusto, notion, vercel, webflow, etc.)
    # have migrated off Lever and now return 404. Run discovery to find live boards.
    # Live-checked on 2026-04-11: these Lever tokens returned working board pages.
    "lever": _normalize_boards(
        [
            "plaid",
            "aircall",
            "metabase",
            "whoop",
            "hive",
            "spotify",
            "regrello",
            "ivo",
            "bumbleinc",
            "supermove",
        ]
    ),
    "ashby": _normalize_boards(
        [
            "notion",
            "openai",
            "replit",
            "perplexity",
            "linear",
            "modal",
            "ramp",
            "mercor",
            "harvey",
            "exa",
            "krea",
            "hud",
            "magical",
            "runway",
            "runway-ml",
            "rillet",
            "adaptivesecurity",
        ]
    ),
}


def bootstrap_board_targets() -> dict[str, list[str]]:
    return {
        source_name: list(boards)
        for source_name, boards in BOOTSTRAP_PORTAL_BOARDS.items()
    }


def default_portal_sources_payload() -> dict[str, dict[str, Any]]:
    return {
        source_name: (
            {
                "enabled": True,
                "boards": [],
                "seed_urls": [],
                "seed_domains": [],
            }
            if source_name == "greenhouse"
            else {
                "enabled": False,
                "boards": [],
                "seed_urls": [],
                "seed_domains": [],
            }
        )
        for source_name in BOOTSTRAP_PORTAL_BOARDS
    }


def default_portals_payload() -> dict[str, Any]:
    return {
        "sources": default_portal_sources_payload(),
        "tracked_companies": [],
    }
